/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_example_ayush_augmentedreality_OpenCVClass */

using namespace cv;
using namespace std;

#ifndef _Included_com_example_ayush_augmentedreality_OpenCVClass
#define _Included_com_example_ayush_augmentedreality_OpenCVClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ayush_augmentedreality_OpenCVClass
 * Method:    faceDetection
 * Signature: (J)V
 */
void detectFace(Mat &frame);
void detectHuman(Mat &frame);

JNIEXPORT void JNICALL Java_com_example_ayush_augmentedreality_OpenCVClass_faceDetection
        (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_example_ayush_augmentedreality_OpenCVClass_humanDetection
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
